name: tests

on:
  push:
    paths:
      - "location_allocation/**"
      - "tests/**"
      - ".github/workflows/ci-tests.yml"
      - "setup.py"
      - "pyproject.toml"
      - ".coveragerc"
  pull_request:
    branches:
      - master
    paths:
      - "location_allocation/**"
      - "tests/**"
      - ".github/workflows/ci-tests.yml"
      - "setup.py"
      - "pyproject.toml"
      - ".coveragerc"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9, pypy-3.7]
        os: [macos-latest, ubuntu-18.04, ubuntu-16.04, ubuntu-20.04, windows-2019, windows-2016]
        https://github.com/actions/virtual-environments/issues/2017
        exclude:
          # excludes pypy Windows because only 32 bit pypy is supported.
          - os: windows-2019
            python_version: pypy-3.7
          - os: windows-2016
            python_version: pypy-3.7
          # temporarily exclude pypy3 on macos
          - os: macos-latest
            python_version: pypy-3.7
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
#     From https://github.com/python-poetry/poetry/actions
    - name: Get full python version
      id: full-python-version
      run: |
        echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info[:3]))")
        echo ::set-output name=versionshort::$(python -c "import sys; print(''.join(str(v) for v in sys.version_info[:2]))")
    - name: Install and set up Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry config virtualenvs.in-project true
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: |
        source $HOME/.poetry/env
        poetry install
    - name: style & lint checks
      run: |
        source .venv/bin/activate
        pre-commit run
    - name: pytest
      run: |
        source .venv/bin/activate
        pytest --cov=location_allocation tests/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}